# External Secrets lee GCP Secret Manager con Workload Identity (sin llaves).
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: project-2cbee419-ed7b-469e-89d
